language: node_js
node_js: stable
addons:
  chrome: stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
cache: npm
env:
  global:
    - secure: JMRvm+Pj3mTEcrhFNZTnKShuHISqGX+mR4ICFwWT8zEKF/mMosRQsVBf7xVc5DXB0x3CxjP/CauVG98/0AktVwmP1sEp0g+FFePFzux+VzvDbmynX3kkpgS82Sq11Rp6YnYb85pLjCMUG6pKCNkp8XMkcW7IX9c9AYrRgsXmQEY=
    - secure: fZzj04OSXUCcScIxxjsqFIyZ+RE22fAVDG/qx73sU9BqjvhOLrUFsxYVOcYARgBfzNuf3c0mB5GI//hyIRfAFCgx6bqYG8erN/VoryPBREnN5fGvR/AkrFzJeJ/2AlcHpXqWyQnlLXZwfUb1RBidYYzhEUAfEso0AyMoWJzgFQs=
